"""sch_number on signals and projects

Revision ID: 019c1612f4f7
Revises: c2d5f8b31a44
Create Date: 2026-08-05 21:53:54.314122
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '019c1612f4f7'
down_revision = 'c2d5f8b31a44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('sch_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_projects_sch_number'), 'projects', ['sch_number'], unique=False)
    op.add_column('signals', sa.Column('sch_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_signals_sch_number'), 'signals', ['sch_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_sch_number'), table_name='signals')
    op.drop_column('signals', 'sch_number')
    op.drop_index(op.f('ix_projects_sch_number'), table_name='projects')
    op.drop_column('projects', 'sch_number')
    # ### end Alembic commands ###
