"""contact source flag

Adds contacts.source (manual | filing | apollo | lusha), backfilled to
'manual' for every existing row -- every Contact row written before this
migration came from the dashboard's manual "add contact" form, the only
write path that existed. See app/models.py:Contact.source and
app/enrichment.py.

Revision ID: 18a93f30c146
Revises: e47e9c174942
Create Date: 2026-08-07 20:57:38.215840
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '18a93f30c146'
down_revision = 'e47e9c174942'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default lets the ALTER fill existing rows without a table rewrite.
    op.add_column('contacts', sa.Column(
        'source', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='manual'))
    op.create_index(op.f('ix_contacts_source'), 'contacts', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_source'), table_name='contacts')
    op.drop_column('contacts', 'source')
    # ### end Alembic commands ###
