"""false positive marks

Revision ID: 309c1285d582
Revises: 69a97b7a7c2b
Create Date: 2026-08-04 22:09:05.671698
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '309c1285d582'
down_revision = '69a97b7a7c2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('false_positive_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score_at_mark', sa.Float(), nullable=False),
    sa.Column('window_at_mark', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_false_positive_marks_project_id'), 'false_positive_marks', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_false_positive_marks_project_id'), table_name='false_positive_marks')
    op.drop_table('false_positive_marks')
    # ### end Alembic commands ###
