"""iepr forward load layer

One table: iepr_forward_loads. A county-level forward-MW layer imported by
hand, twice a year, from a utility's CEC IEPR large-load forecast filing (see
app/pipeline/iepr.py). Redacted to status/city/region/MW at the source, so it
can never name a lead — it exists to feed Phase 4's county-adjacency
spillover score, not to detect projects.

Revision ID: 5b2a4266f288
Revises: b3d7e1a94c62
Create Date: 2026-08-07 12:14:06.066255
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '5b2a4266f288'
down_revision = 'b3d7e1a94c62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iepr_forward_loads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utility', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('docket_tn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cec_grouping', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('county', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('voltage', sa.Float(), nullable=True),
    sa.Column('requested_energization_year', sa.Integer(), nullable=True),
    sa.Column('requested_peak_mw', sa.Float(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iepr_forward_loads_county'), 'iepr_forward_loads', ['county'], unique=False)
    op.create_index(op.f('ix_iepr_forward_loads_docket_tn'), 'iepr_forward_loads', ['docket_tn'], unique=False)
    op.create_index(op.f('ix_iepr_forward_loads_imported_at'), 'iepr_forward_loads', ['imported_at'], unique=False)
    op.create_index(op.f('ix_iepr_forward_loads_state'), 'iepr_forward_loads', ['state'], unique=False)
    op.create_index(op.f('ix_iepr_forward_loads_utility'), 'iepr_forward_loads', ['utility'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iepr_forward_loads_utility'), table_name='iepr_forward_loads')
    op.drop_index(op.f('ix_iepr_forward_loads_state'), table_name='iepr_forward_loads')
    op.drop_index(op.f('ix_iepr_forward_loads_imported_at'), table_name='iepr_forward_loads')
    op.drop_index(op.f('ix_iepr_forward_loads_docket_tn'), table_name='iepr_forward_loads')
    op.drop_index(op.f('ix_iepr_forward_loads_county'), table_name='iepr_forward_loads')
    op.drop_table('iepr_forward_loads')
    # ### end Alembic commands ###
