"""production hardening: spend, http_log, firms, outcomes, backfill, territory

Revision ID: 69a97b7a7c2b
Revises: 89ae95774b11
Create Date: 2026-08-04 21:47:29.124219
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '69a97b7a7c2b'
down_revision = '89ae95774b11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backfill_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_new', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'chunk_key', name='uq_backfill_chunk')
    )
    op.create_index(op.f('ix_backfill_checkpoints_source'), 'backfill_checkpoints', ['source'], unique=False)
    op.create_table('firms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_norm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('firm_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('added_from', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_norm', name='uq_firm_norm')
    )
    op.create_index(op.f('ix_firms_name'), 'firms', ['name'], unique=False)
    op.create_index(op.f('ix_firms_name_norm'), 'firms', ['name_norm'], unique=False)
    op.create_table('token_spend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('day', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_spend_day'), 'token_spend', ['day'], unique=False)
    op.create_index(op.f('ix_token_spend_ts'), 'token_spend', ['ts'], unique=False)
    op.create_table('http_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_run_id', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('response_bytes', sa.Integer(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['source_run_id'], ['source_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_http_log_source_run_id'), 'http_log', ['source_run_id'], unique=False)
    op.create_table('outcome_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcome_events_project_id'), 'outcome_events', ['project_id'], unique=False)
    op.create_table('project_firms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'firm_id', 'role', name='uq_project_firm_role')
    )
    op.create_index(op.f('ix_project_firms_firm_id'), 'project_firms', ['firm_id'], unique=False)
    op.create_index(op.f('ix_project_firms_project_id'), 'project_firms', ['project_id'], unique=False)
    op.add_column('projects', sa.Column('estimate_low_confidence', sa.Boolean(), nullable=False))
    op.add_column('projects', sa.Column('in_territory', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_projects_in_territory'), 'projects', ['in_territory'], unique=False)
    op.create_index(op.f('ix_projects_last_signal_at'), 'projects', ['last_signal_at'], unique=False)
    op.create_index(op.f('ix_projects_stage'), 'projects', ['stage'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_stage'), table_name='projects')
    op.drop_index(op.f('ix_projects_last_signal_at'), table_name='projects')
    op.drop_index(op.f('ix_projects_in_territory'), table_name='projects')
    op.drop_column('projects', 'in_territory')
    op.drop_column('projects', 'estimate_low_confidence')
    op.drop_index(op.f('ix_project_firms_project_id'), table_name='project_firms')
    op.drop_index(op.f('ix_project_firms_firm_id'), table_name='project_firms')
    op.drop_table('project_firms')
    op.drop_index(op.f('ix_outcome_events_project_id'), table_name='outcome_events')
    op.drop_table('outcome_events')
    op.drop_index(op.f('ix_http_log_source_run_id'), table_name='http_log')
    op.drop_table('http_log')
    op.drop_index(op.f('ix_token_spend_ts'), table_name='token_spend')
    op.drop_index(op.f('ix_token_spend_day'), table_name='token_spend')
    op.drop_table('token_spend')
    op.drop_index(op.f('ix_firms_name_norm'), table_name='firms')
    op.drop_index(op.f('ix_firms_name'), table_name='firms')
    op.drop_table('firms')
    op.drop_index(op.f('ix_backfill_checkpoints_source'), table_name='backfill_checkpoints')
    op.drop_table('backfill_checkpoints')
    # ### end Alembic commands ###
