"""initial schema

Revision ID: 89ae95774b11
Revises: 
Create Date: 2026-08-04 21:14:32.279710
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '89ae95774b11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('territory', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_company'), 'contacts', ['company'], unique=False)
    op.create_index(op.f('ix_contacts_name'), 'contacts', ['name'], unique=False)
    op.create_table('developer_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alias_norm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('learned_from', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_norm', name='uq_alias_norm')
    )
    op.create_index(op.f('ix_developer_aliases_alias_norm'), 'developer_aliases', ['alias_norm'], unique=False)
    op.create_table('digest_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'ref_id', 'fingerprint', name='uq_digest_item')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('developer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('county', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('apn_parcel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mw_it', sa.Float(), nullable=True),
    sa.Column('mw_total', sa.Float(), nullable=True),
    sa.Column('tons_estimate_low', sa.Float(), nullable=True),
    sa.Column('tons_estimate_high', sa.Float(), nullable=True),
    sa.Column('estimate_basis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stage', sa.Enum('concept', 'entitlement', 'design', 'permitting', 'procurement', 'construction', 'operating', 'unknown', name='stage'), nullable=False),
    sa.Column('window', sa.Enum('PRE_BOD', 'IN_BOD', 'POST_BOD', 'OPERATING', name='window'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('days_to_estimated_bid', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_signal_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('next_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('next_action_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_county'), 'projects', ['county'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_score'), 'projects', ['score'], unique=False)
    op.create_table('raw_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('triage_result', sa.Enum('pending', 'relevant', 'irrelevant', 'error', name='triageresult'), nullable=False),
    sa.Column('triage_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_uid', name='uq_source_uid')
    )
    op.create_index(op.f('ix_raw_documents_content_hash'), 'raw_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_raw_documents_source'), 'raw_documents', ['source'], unique=False)
    op.create_index(op.f('ix_raw_documents_source_uid'), 'raw_documents', ['source_uid'], unique=False)
    op.create_index(op.f('ix_raw_documents_triage_result'), 'raw_documents', ['triage_result'], unique=False)
    op.create_table('source_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_new', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_runs_source'), 'source_runs', ['source'], unique=False)
    op.create_table('outreach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('next_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('next_action_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_project_id'), 'outreach', ['project_id'], unique=False)
    op.create_table('project_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'contact_id', 'role', name='uq_project_contact_role')
    )
    op.create_index(op.f('ix_project_contacts_contact_id'), 'project_contacts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_project_contacts_project_id'), 'project_contacts', ['project_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_document_id', sa.Integer(), nullable=True),
    sa.Column('signal_type', sa.Enum('utility_load_request', 'land_transfer', 'abatement_application', 'ceqa_nop', 'planning_agenda', 'job_posting', 'air_permit_atc', 'water_will_serve', 'ceqa_deir', 'engineer_move', 'faa_7460', 'abs_issuance', 'news_report', 'prequal_invite', 'bid_invite', 'manual_tip', name='signaltype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('project_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('developer_or_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jurisdiction', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('county', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('street_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('apn_parcel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('mw_it', sa.Float(), nullable=True),
    sa.Column('mw_total', sa.Float(), nullable=True),
    sa.Column('generator_count', sa.Integer(), nullable=True),
    sa.Column('generator_hp_each', sa.Float(), nullable=True),
    sa.Column('generator_kw_each', sa.Float(), nullable=True),
    sa.Column('building_sqft', sa.Float(), nullable=True),
    sa.Column('acres', sa.Float(), nullable=True),
    sa.Column('building_count', sa.Integer(), nullable=True),
    sa.Column('cooling_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('water_acre_feet_per_year', sa.Float(), nullable=True),
    sa.Column('stage', sa.Enum('concept', 'entitlement', 'design', 'permitting', 'procurement', 'construction', 'operating', 'unknown', name='stage'), nullable=False),
    sa.Column('filing_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary_one_line', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_json', sa.JSON(), nullable=False),
    sa.Column('named_people', sa.JSON(), nullable=False),
    sa.Column('named_firms', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_county'), 'signals', ['county'], unique=False)
    op.create_index(op.f('ix_signals_raw_document_id'), 'signals', ['raw_document_id'], unique=False)
    op.create_index(op.f('ix_signals_signal_type'), 'signals', ['signal_type'], unique=False)
    op.create_table('match_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('llm_verdict', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('llm_reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_candidates_project_id'), 'match_candidates', ['project_id'], unique=False)
    op.create_index(op.f('ix_match_candidates_signal_id'), 'match_candidates', ['signal_id'], unique=False)
    op.create_index(op.f('ix_match_candidates_status'), 'match_candidates', ['status'], unique=False)
    op.create_table('project_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('match_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'signal_id', name='uq_project_signal')
    )
    op.create_index(op.f('ix_project_signals_project_id'), 'project_signals', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_signals_signal_id'), 'project_signals', ['signal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_signals_signal_id'), table_name='project_signals')
    op.drop_index(op.f('ix_project_signals_project_id'), table_name='project_signals')
    op.drop_table('project_signals')
    op.drop_index(op.f('ix_match_candidates_status'), table_name='match_candidates')
    op.drop_index(op.f('ix_match_candidates_signal_id'), table_name='match_candidates')
    op.drop_index(op.f('ix_match_candidates_project_id'), table_name='match_candidates')
    op.drop_table('match_candidates')
    op.drop_index(op.f('ix_signals_signal_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_raw_document_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_county'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_project_contacts_project_id'), table_name='project_contacts')
    op.drop_index(op.f('ix_project_contacts_contact_id'), table_name='project_contacts')
    op.drop_table('project_contacts')
    op.drop_index(op.f('ix_outreach_project_id'), table_name='outreach')
    op.drop_table('outreach')
    op.drop_index(op.f('ix_source_runs_source'), table_name='source_runs')
    op.drop_table('source_runs')
    op.drop_index(op.f('ix_raw_documents_triage_result'), table_name='raw_documents')
    op.drop_index(op.f('ix_raw_documents_source_uid'), table_name='raw_documents')
    op.drop_index(op.f('ix_raw_documents_source'), table_name='raw_documents')
    op.drop_index(op.f('ix_raw_documents_content_hash'), table_name='raw_documents')
    op.drop_table('raw_documents')
    op.drop_index(op.f('ix_projects_score'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_county'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('digest_log')
    op.drop_index(op.f('ix_developer_aliases_alias_norm'), table_name='developer_aliases')
    op.drop_table('developer_aliases')
    op.drop_index(op.f('ix_contacts_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_company'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
