"""spillover score fields

Two nullable columns on projects: spillover_mw (raw county+adjacent recent/
queued DC MW at last scoring run) and spillover_basis (the human-readable
"why", shown on the board row). See app/pipeline/spillover.py.

Revision ID: e47e9c174942
Revises: 5b2a4266f288
Create Date: 2026-08-07 13:57:34.643814
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = 'e47e9c174942'
down_revision = '5b2a4266f288'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('spillover_mw', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('spillover_basis', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'spillover_basis')
    op.drop_column('projects', 'spillover_mw')
    # ### end Alembic commands ###
