"""accounts module: product lines, accounts, coverage

Three new tables for the ~100 dormant-account assignment: product_lines (the
DMG/ToroAire line card, seeded from config.yaml — see app/accounts.py), accounts
(the sales-pipeline company record, distinct from firms — see the Account
docstring in app/models.py for why it isn't just an extra column on Firm), and
account_coverage (one row per account per line: bought/quoted_not_won/
never_quoted/unknown, plus install year and dollar value where known).

Nothing here touches the project pipeline's tables.

Revision ID: fc46871532b3
Revises: e4f7b2d81c69
Create Date: 2026-08-06 22:23:58.613256
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = 'fc46871532b3'
down_revision = 'e4f7b2d81c69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_norm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('firm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subcategory', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value_tier', sa.Integer(), nullable=False),
    sa.Column('equipment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_norm', name='uq_product_line_norm')
    )
    op.create_index(op.f('ix_product_lines_category'), 'product_lines', ['category'], unique=False)
    op.create_index(op.f('ix_product_lines_name'), 'product_lines', ['name'], unique=False)
    op.create_index(op.f('ix_product_lines_name_norm'), 'product_lines', ['name_norm'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_norm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('county', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('assigned_rep', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_order_date', sa.DateTime(), nullable=True),
    sa.Column('last_order_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('ownership_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_type'), 'accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_accounts_assigned_rep'), 'accounts', ['assigned_rep'], unique=False)
    op.create_index(op.f('ix_accounts_county'), 'accounts', ['county'], unique=False)
    op.create_index(op.f('ix_accounts_firm_id'), 'accounts', ['firm_id'], unique=False)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    op.create_index(op.f('ix_accounts_name_norm'), 'accounts', ['name_norm'], unique=False)
    op.create_index(op.f('ix_accounts_parent_id'), 'accounts', ['parent_id'], unique=False)
    op.create_index(op.f('ix_accounts_status'), 'accounts', ['status'], unique=False)
    op.create_table('account_coverage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('product_line_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('install_year', sa.Integer(), nullable=True),
    sa.Column('dollar_value', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['product_line_id'], ['product_lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'product_line_id', name='uq_account_line')
    )
    op.create_index(op.f('ix_account_coverage_account_id'), 'account_coverage', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_coverage_product_line_id'), 'account_coverage', ['product_line_id'], unique=False)
    op.create_index(op.f('ix_account_coverage_status'), 'account_coverage', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_coverage_status'), table_name='account_coverage')
    op.drop_index(op.f('ix_account_coverage_product_line_id'), table_name='account_coverage')
    op.drop_index(op.f('ix_account_coverage_account_id'), table_name='account_coverage')
    op.drop_table('account_coverage')
    op.drop_index(op.f('ix_accounts_status'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_parent_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_name_norm'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_firm_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_county'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_assigned_rep'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_type'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_product_lines_name_norm'), table_name='product_lines')
    op.drop_index(op.f('ix_product_lines_name'), table_name='product_lines')
    op.drop_index(op.f('ix_product_lines_category'), table_name='product_lines')
    op.drop_table('product_lines')
    # ### end Alembic commands ###
